menu:
- {name: 'Home', url: '/'}
- {name: 'News', url: '/news'}
- {name: 'Learn', url: '/learn'}
- {name: 'Discord', url: '/discord'}
- {name: 'About', url: '/about'}
- {name: 'Search', url: '/search'}

social:
- {icon: 'github', link: 'https://github.com/zhutaosheng'}
- {icon: 'instagram', link: 'https://www.instagram.com/zhutao.s/?utm_source=ig_embed&utm_campaign=loading'}
