menu:
- {name: 'Home', url: '/'}
  - {name: 'Home', url: '/'}
- {name: 'Blog', url: '/blog'}
  - - {name: 'Home', url: '/'}
- {name: 'Resources', url: '/resources'}

social:
- {icon: 'github', link: 'https://github.com/zhutaosheng'}
- {icon: 'instagram', link: 'https://www.instagram.com/zhutao.s/?utm_source=ig_embed&utm_campaign=loading'}
